server:
  port: 8000
spring:
  datasource:
    username: root
    password: 123
    #driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.195.131:3306/gmall_ums
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.195.131:8848
  application:
    name: gmall-member
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto